USE FACTURACION;
EXEC sp_addtype valorreal, "DECIMAL(6,2)", NULL;
EXEC sp_addtype entero, "INT";

CREATE TABLE PRODUCTOS(
    cvePto entero,
    descripcion VARCHAR(30),
    precio valorreal,
    cveLinea entero,
    tipo VARCHAR(20),
);
CREATE TABLE LINEAS(
    cveLinea entero,
);
ALTER TABLE PRODUCTOS ALTER COLUMN cvePto INT NOT NULL;
ALTER TABLE PRODUCTOS ADD CONSTRAINT PK_PRODUCTOS PRIMARY KEY (cvePto);
ALTER TABLE PRODUCTOS ADD CONSTRAINT FK_PRODUCTOS_LINEAS FOREIGN KEY (cveLinea) REFERENCES LINEAS(cveLinea);
ALTER TABLE LINEAS ADD CONSTRAINT CK_CLAVELINEA CHECK (cveLinea > 1 AND cveLinea < 20);

ALTER TABLE LINEAS ADD Descripcion VARCHAR(30);
ALTER TABLE LINEAS ADD CONSTRAINT CK_DESCRIPCION CHECK (descripcion LIKE 'Lin%');
ALTER TABLE PRODUCTOS ADD CONSTRAINT CK_PRECIO CHECK (precio > 1.00 AND precio <9999.99);
ALTER TABLE PRODUCTOS ADD CONSTRAINT D_TIPO DEFAULT 'OFICINA' FOR tipo; 

INSERT INTO LINEAS VALUES(1, 'Linea 1');
INSERT INTO PRODUCTOS VALUES(1, 'Producto 1', 100.00, 1, 'OFICINA');
