USE ORDERSDB;
-- 1.Mediante restricción crea las llaves primarias compuestas y llaves foráneas de las tablas Supplies y la tabla Contains.
-- ALTER TABLE SUPPLIER ADD CONSTRAINT PK_SUPPLIER PRIMARY KEY(supplerNo);
-- ALTER TABLE CUSTOMER ADD CONSTRAINT PK_CUSTOMER PRIMARY KEY(custId);
-- ALTER TABLE ORDERS ADD CONSTRAINT PK_ORDERS PRIMARY KEY(orderNo);
-- ALTER TABLE ITEM ADD CONSTRAINT PK_ITEM PRIMARY KEY(itemNo);

-- ALTER TABLE ORDERITEM ADD CONSTRAINT PK_ORDERITEM PRIMARY KEY(orderNo, itemNo);
-- ALTER TABLE SUPPLERITEM ADD CONSTRAINT PK_SUPPLIERITEM PRIMARY KEY(itemNo, supplerNo);


-- ALTER TABLE ORDERITEM ADD CONSTRAINT FK_ORDERITEM_ORDER FOREIGN KEY(orderNo) REFERENCES ORDERS(orderNo);
-- ALTER TABLE ORDERITEM ADD CONSTRAINT FK_ORDERITEM_ITEM FOREIGN KEY(itemNo) REFERENCES ITEM(itemNo);

-- ALTER TABLE SUPPLERITEM ADD CONSTRAINT FK_SUPPLIERITEM_ITEM FOREIGN KEY(itemNo) REFERENCES ITEM(itemNo);
-- ALTER TABLE SUPPLERITEM ADD CONSTRAINT FK_SUPPLIERITEM_SUPPLIER FOREIGN KEY(supplerNo) REFERENCES SUPPLIER(supplerNo);

