USE T9;
-- CREATE TABLE EMPLEADO (
--     apellidos VARCHAR(20),
--     idDepartamento INTEGER,
-- );
-- CREATE TABLE DEPARTAMENTO (
--     nombre VARCHAR(20),
--     idDepartamento INTEGER,
-- );

-- INSERT INTO DEPARTAMENTO VALUES ('Ingenieria', 33);
-- INSERT INTO DEPARTAMENTO VALUES ('Ventas', 31);
-- INSERT INTO DEPARTAMENTO VALUES ('Produccion', 34);
-- INSERT INTO DEPARTAMENTO VALUES ('Mercadeo', 35);

-- INSERT INTO EMPLEADO VALUES ('Andrade', 31);
-- INSERT INTO EMPLEADO VALUES ('Jordan', 33);
-- INSERT INTO EMPLEADO VALUES ('Steinberg', 33);
-- INSERT INTO EMPLEADO VALUES ('Robinson', 34);
-- INSERT INTO EMPLEADO VALUES ('Zolano', 34);
-- INSERT INTO EMPLEADO VALUES ('Gaspar', 36);
SELECT * FROM EMPLEADO, DEPARTAMENTO WHERE EMPLEADO.idDepartamento = DEPARTAMENTO.idDepartamento;